- name: Install Certbot Google DNS plugin
  snap:
    name: certbot-dns-cloudflare
- name: Create CloudFlare credentials file
  ini_file:
    path: "{{ certbot_dns_cloudflare_credentials_file_dest }}"
    section: null
    option: dns_cloudflare_api_token
    value: "{{ certbot_dns.cloudflare_api_token }}"
    owner: root
    group: root
    mode: 0600
- name: Get a certificate using dns-01 with CloudFlare
  command: |
    certbot certonly \
      --dns-cloudflare \
      --dns-cloudflare-credentials {{ certbot_dns_cloudflare_credentials_file_dest }} \
      --dns-cloudflare-propagation-seconds {{ certbot_dns_cloudflare_propagation_seconds }} \
      --server {{ certbot_server }} \
      --agree-tos \
      -m {{ certbot_email }} \
      --cert-name {{ wordpress_http_hosts | first }} \
      -d {{ wordpress_http_hosts | join(' -d ') }} \
      -d www.{{ wordpress_http_hosts | join(' -d www.') }}
  args:
    creates: /etc/letsencrypt/live/{{ wordpress_http_hosts | first }}
