php_modules:
  - php-curl
  - php-gd
  - php-mbstring
  - php-xml
  - php-xmlrpc
  - php-soap
  - php-intl
  - php-zip
  - php-imagick
  - php-json

nginx_add_header:
  - "X-Frame-Options SAMEORIGIN"
  - "X-Content-Type-Options nosniff"
  - "X-XSS-Protection \"1; mode=block\""
  - "Strict-Transport-Security max-age=15768000"
  - "Content-Security-Policy \"script-src 'self' 'unsafe-inline' 'unsafe-eval'; object-src 'self'\""

nginx_client_max_body_size: 100M
php_upload_max_filesize: 100M
php_post_max_size: 100M

mysql_hardening_enabled: true
mysql_hardening_user: mysql
mysql_datadir: /var/lib/mysql
mysql_hardening_mysql_hardening_conf_file: /etc/mysql/conf.d/hardening.cnf
mysql_root_password: "{{ lookup('password', '.credentials/mysql/root length=32') }}"

wordpress_mysql_password: "{{ lookup('password', '.credentials/mysql/wordpress length=32') }}"

certbot_server: https://acme-staging-v02.api.letsencrypt.org/directory
